services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: lysi
      POSTGRES_PASSWORD: lysi
      POSTGRES_DB: lysi
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lysi"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
